name: Avram CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.0
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check src spec config
  ameba:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.0
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install
      - name: Analyze
        run: crystal bin/ameba.cr
